Nuvalence/dialogflow-cx-tools

cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/JsonSnippets.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/Ssml.kt

If the fulfillment message already has SSML speak tags, do not apply the SSML conversion, just copy it.

UICCAI-552

---

cx-phrases/README.md
cx-phrases/defaults.conf
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/Ssml.kt
cx-phrases/src/test/kotlin/io/nuvalence/cx/tools/phrases/SsmlKtTest.kt

- add support for language-specific match/replace rules
- add use cases from ticket (https://dol-ewf.atlassian.net/browse/UICCAI-748)
- updated tests accordingly
- updated documentation on use/purpose
To Test:
These cases should be covered by the unit test cases, but extra validation/checking can be done by writing test strings in a test case and verifying the generated ssml sounds as expected using Google's TTS API.

UICCAI-748: Import tool SSML tweaks

---

cx-shared/src/main/kotlin/io/nuvalence/cx/tools/shared/SheetCopier.kt
cx-shared/src/main/kotlin/io/nuvalence/cx/tools/shared/SheetReader.kt
cx-shared/src/main/kotlin/io/nuvalence/cx/tools/shared/SheetWriter.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/artifact/SpreadsheetArtifact.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/extension/SmokeTestExtension.kt

Running the test framework should now include the agent path in both the test report output and spreadsheet artifact as follows:

UICCAI-585: added agent path to test report output and spreadsheet artifact

---

cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/assertion/Assertions.kt

Tested with the following matching modes:
Normal:
[test.zip](https://github.com/Nuvalence/dialogflow-cx-tools/files/12612718/test.zip)
Adaptive:
[test_adaptive.zip](https://github.com/Nuvalence/dialogflow-cx-tools/files/12612727/test_adaptive.zip)

UICCAI-587: assertions changed to assert on outputAudioText SSML

---

README.md
cx-phrases/defaults.conf
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/Ssml.kt

Changes include:
- fix for percentages to match numbers using , instead of . as decimal
- fix pronunciations of `DOL` (changed to `D O L`), `PIN` (changed to `pin`), `partialui` (changed to `partial U I`), and `NY` in addresses (changed to `N Y` in other languages and `New York` in English)

UICCAI-748: fix pronunciations, percentage match regex

---

cx-test/build.gradle.kts
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/DFCXTestBuilderSpec.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/E2ESpec.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/extension/DFCXTestBuilderExtension.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/extension/SmokeTestExtension.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/model/DFCXTestBuilderResult.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/testsource/DFCXTestBuilderTestSource.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/testsource/E2EFormatReader.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/testsource/FormatReader.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/testsource/SmokeFormatReader.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/util/Properties.kt

* Added DFCX Test Builder spec and corresponding scaffolding
* Added test source to procure (and later filter) test cases
* Added test extension to handle beforeAll handler (test procurement and kickoff), afterEach handler (test result handling, and later persistence in memory), afterAll handler (resource cleanup), and argument provision for test run
* Added test builder result model to support extended test result information (for later persistence in artifact spreadsheet)
* Changed default test run to dfcx spec
* Refactored sheetreaders into testsource package for consistency 
https://dol-ewf.atlassian.net/browse/UICCAI-861
https://dialogflow.cloud.google.com/cx/projects/dol-uisim-ccai-dev-app/locations/global/agents/997f91c8-6a5b-4852-9621-f933faa7fa13
Run the following command:
``` …
```

UICCAI-861: added DFCX Test Builder spec, refactors

---

cx-test/README.md
cx-test/build.gradle.kts
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/testsource/DFCXTestBuilderTestSource.kt
cx-test/src/test/kotlin/io/nuvalence/cx/tools/cxtest/util/Properties.kt

* Added tag filtering to DFCX Test Builder spec
* Behavior outlined in readme
https://dol-ewf.atlassian.net/browse/UICCAI-865
https://dialogflow.cloud.google.com/cx/projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0-3ba2a92fde4e
Run the following commands:
Default test:
```
./gradlew cx-test:test --info -PagentPath="projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0-3ba2a92fde4e" 
```
All test:
```
./gradlew cx-test:test --info -PagentPath="projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0-3ba2a92fde4e" -PdfcxTagFilter="ALL"
```
Filter test:
```
./gradlew cx-test:test --info -PagentPath="projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0-3ba2a92fde4e" …
```

UICCAI-865: add DFCX test tags

---

cx-phrases/defaults.conf
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/Ssml.kt
cx-phrases/src/test/kotlin/io/nuvalence/cx/tools/phrases/SsmlKtTest.kt

Since parameters are not interpreted until "runtime" (say-time?), some don't get proper SSML around them and they are pronounced weird. This adds parameters with `phone-number` in them to the phone-number regex, allowing it to be interpreted correctly, as well as manually adding regex matching for `dmv-id`, `dmv-doc-id` and "DD214" to pronounce those strings correctly.

UICCAI-1034: add support for wrapping parameters in SSML

---

cx-phrases/defaults.conf
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/Ssml.kt
cx-phrases/src/test/kotlin/io/nuvalence/cx/tools/phrases/SsmlKtTest.kt

This changes ssml wrapping to happen with numbers of length 5 or more since 4 accidentally picks up years. Also added a special case for a 4 digit PO box number we had that was being pronounced wrong.
To test, see the SSML on https://dialogflow.cloud.google.com/cx/projects/dol-uisim-ccai-dev-app/locations/global/agents/0fd9454d-9fee-4177-809d-573ccf0dd355/flows/a6f7dd04-121c-44c9-ae2a-39ee7d40efcf/flow_creation?pageId=cdadc50f-f4f1-40e8-90d2-8cd230f3d088 and verify that "2014" is pronounced correctly when speaking through the SSML tester https://cloud.google.com/text-to-speech/#section-2

UICCAI-1061: ignore numbers less than 4 characters in length for ssml processing

---

cx-test-sync/src/main/kotlin/io/nuvalence/cx/tools/cxtestsync/source/artifact/DFCXSpreadsheetArtifactSource.kt
cx-test-sync/src/main/kotlin/io/nuvalence/cx/tools/cxtestsync/source/test/DFCXTestBuilderTestSource.kt
cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/DFCXTestBuilderSpec.kt

* Added support for DTMF and event inputs in the test spreadsheet artifact
* Such inputs are prefixed with [DTMF] and [EVENT]
* DTMF inputs are suffixed with `|${finishDigit}` if finish digit is present
https://dol-ewf.atlassian.net/browse/UICCAI-1024
https://dialogflow.cloud.google.com/cx/projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0-3ba2a92fde4e
1. Ensure that the agent has tests that make use of DMTF and events. The above agent has been edited to include test event implementations as the actual agent does not currently use events.
2. Create a file `cx-test/main/resources/default.properties` with the following contents:
```
credentialsUrl=file:///path/to/creds.json
agentPath=projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0- …
```

UICCAI-1024: DTMF/event input support

---

cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/extension/DFCXTestBuilderExtension.kt
cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/testsource/DFCXTestBuilderTestSource.kt

* Added support for tag filter exclusions in properties
* Simply prefix tags with `!` to exclude them 
https://dol-ewf.atlassian.net/browse/UICCAI-1025
https://dialogflow.cloud.google.com/cx/projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0-3ba2a92fde4e
1. Create a file `cx-test/main/resources/default.properties` with the following contents:
```
credentialsUrl=file:///path/to/creds.json
agentPath=projects/dol-uisim-ccai-dev-app/locations/global/agents/7d8acdfb-e622-4b98-bcd0-3ba2a92fde4e
dfcxEndpoint=dialogflow.googleapis.com:443
dfcxTagFilter=#OC,!#E2E
```
(any of these properties can be replaced as needed)
2. Run tests
```
./gradlew cx-test:run --args src/main/resources/default.properties
```
3. Ensure that the resulting spreadsheet only has tests tagged OC …

UICCAI-1025: tag filter exclusion

---

cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/AgentLanguageMerger.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/JsonSnippets.kt

To test this: 
1. checkout main in the agent
2. checkout this branch in the import tool
3. run `export`, then `import` commands (feel free to ask me for the run configurations for these in IntelliJ if you don't have them)
4. copy the "imported" agent files to agent-p2 directory for the agent and rewrite everything, then run `npm run format`
5. Observe the git diffs and make sure the only changes are related to SSML output audio text generation; there shouldn't be languageCode or setParameterActions blocks changing places

UICCAI-1103: fix languageCode and other ordering bugs

---

cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/AgentLanguageMerger.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/AgentPhrasesExtractor.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/Exporter.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/JsonSnippets.kt

This branched off of work from https://github.com/Nuvalence/dialogflow-cx-tools/pull/42, so merge that first.
To test this: 
1. checkout main in the agent
2. checkout this branch in the import tool
3. run `export`, then `import` commands (feel free to ask me for the run configurations for these in IntelliJ if you don't have them)
4. copy the "imported" agent files to agent-p2 directory for the agent and rewrite everything, then run `npm run format`
5. Observe the git diffs and make sure chips custom payloads are not removed

UICCAI-1151/1152: add chips text extraction and export to spreadsheet, import/translation support

---

cx-test-sync/README.md
cx-test-sync/src/main/kotlin/io/nuvalence/cx/tools/cxtestsync/processor/SpreadsheetProcessor.kt
cx-test-sync/src/main/kotlin/io/nuvalence/cx/tools/cxtestsync/source/test/DFCXTestBuilderTestSource.kt
cx-test-sync/src/main/kotlin/io/nuvalence/cx/tools/cxtestsync/util/Properties.kt
cx-test-sync/src/main/resources/template.properties

Added exporting of agent before applying diffs to local folder in project.
Also updated default property logic to fix the error
for running the test on your machine
you can use the same properties file and along with test, it will download the agent default in the root folder of project.

Agent export

---

cx-phrases/defaults.conf

* Added space between "10" and "99(-)G" in ES output audio text for natural pronunciation
https://dol-ewf.atlassian.net/browse/UICCAI-1409
1. `../gradlew run --args="export <spreadsheetId> <p1m2 agent path> <sheets API creds>"`
2. `../gradlew run --args="import <spreadsheetId> <p1m2 agent path> <target agent path> <sheets API creds>"`
3. Verify that a space has been added between "10" and "99(-)G" in the resulting agent config.
NOTE: While this has been verified by the author, there are also other changes that have occurred in the CMS tool that cause further modifications to the agent configuration, thereby adding noise. As such, the relevant changes had to be cherry-picked for the final agent PR. See: https://github.com/ny/dol-uisim-ccai-agent/pull/624

UICCAI-1409: fix ES pronunciation of 1099-G

---

cx-phrases/defaults.conf

The tool was erroneously replacing `$flow.1099g-year` with `$flow.1099-G <break time="300ms"/>`. This adds a negative lookbehind to make sure it doesn't match `$flow.1099g-year`. 
To test, you can run the export/import process and compare to main and make sure the above replacement does not happen. Alternatively, you can test the replaced regex with a regex matcher. I did both while fixing.

UICCAI-1420: fix 1099g-year parsing

---

cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/DFCXTestBuilderSpec.kt
cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/Launcher.kt
cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/extension/DFCXTestBuilderExtension.kt

* Reworked result collection for DFCX test builder-based tests
* Test assessment now forced to run in singular thread for collection purposes
* Added more detailed logs for result counts/summary
https://dol-ewf.atlassian.net/browse/UICCAI-1390
Run the following command:
```
./gradlew cx-test:run --args src/main/resources/default.properties 
```
where `default.properties` contains the desired properties, such as the following:
```
credentialsUrl=file:///path/to/credentials/file
agentPath=projects/<project>/locations/<location>/agents/<agentPath>
dfcxEndpoint=dialogflow.googleapis.com:443
dfcxTagFilter=!#Submission
testPackage=io.nuvalence.cx.tools.cxtest
```
Example spreadsheet output found [here](https://docs.google.com/spreadsheets/d/1TCbqDyM8F_lql6fuKTY25DryPFinqphfoQ9V-f1trQM/edit#gid=0 …

UICCAI-1390: test result fixes

---

cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/AgentLanguageMerger.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/AgentPhrasesExtractor.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/JsonSnippets.kt

This adds:
- support for buttons/all extra attributes from chips/buttons
- support for importing multiple custom payload types in a single payload
Ticket:
- https://dol-ewf.atlassian.net/browse/UICCAI-1440
To test, check this branch out and run the export command on the agent. Run import and compare diffs to make sure pages with buttons/chips did not have those payloads deleted as before. You can add translations to your sheet for chips/buttons as well to see those added with the correct structure.

UICCAI-1440: add support for multiple custom payload types and added attributes

---

cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/AgentPhrasesExtractor.kt
cx-phrases/src/main/kotlin/io/nuvalence/cx/tools/phrases/JsonSnippets.kt

* Updated CMS export to persist URLs in chatbot chip fulfillments
* URLs are enclosed in bracket immediately following text
* Updated CMS import to read URLs for chatbot chip fulfillments per above spec
https://dol-ewf.atlassian.net/browse/UICCAI-1465
Run the following command:
```
../gradlew run --args="export <spreadsheetId> <agentPath> <credsPath>"
../gradlew run --args="import <spreadsheetId> <agentPath> <newAgentPath> <credsPath>"
```
Example export output found [here](https://docs.google.com/spreadsheets/d/1EItpCS9KmibJjXf8vmza1HB7Juwej-MFuTk840TedEE).
Example import diff (attribute changed based on [official documentation](https://cloud.google.com/dialogflow/cx/docs/concept/integration/dialogflow-messenger/fulfillment#suggestion_chip_response_type)):

UICCAI-1465: added chip URL support in CMS tool

---

README.md
cx-agent/README.md
cx-agent/build.gradle.kts
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/Main.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/compressor/Compressor.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/generator/CxAgentGenerator.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/generator/Generator.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/generator/SheetParser.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/generator/model/CxAgentModel.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/generator/model/Flow.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/generator/model/Intent.kt
cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/generator/model/Smalltalk.kt

This PR does a couple things:
- moves the agent generation logic to the generator directory and structures the cx-agent folder after cx-phrases and cx-test, making the argument `generate` indicate agent generation (while maintaining agent generation functionality)
- adds `zip-restore` command to zip an agent directory and optionally restore it to a DFCX agent
Details are added in the root README and in the cx-agent README

UICCAI-1510: add command to create zip and restore to DFCX agent

---

cx-test/README.md
cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/DFCXTestBuilderSpec.kt
cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/assertion/Assertions.kt
cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/util/Properties.kt
cx-test/src/main/resources/template.properties

* Added functionality to ignore dates when re-asserting on text mismatches
* Wrapped above functionality in config property `noDateMatch`
* https://dol-ewf.atlassian.net/browse/UICCAI-1512
* Before (run on main): https://docs.google.com/spreadsheets/d/1C0h78C-ARILEXQDyzLPxkQS03COUFUsRnfiWm5McXqE
* After: https://docs.google.com/spreadsheets/d/1l4sU5VKMZHARWa3S4qmhQaC_B7Yp2z3w9D_NVJZ5N_M
* After, with configs: https://docs.google.com/spreadsheets/d/14GyCjvUa-caulSmTeS0kVHycvX9sUEfPwrWHn4xVwT8
* Before (config set to false): https://docs.google.com/spreadsheets/d/1fSW_-pqr-Zv6qgMlKx9B4SaLShmXjHjR8lYzL_PD6so
* Before (config null): https://docs.google.com/spreadsheets/d/1rhiGAepiyTR9ZHvnoejVI-PJ4jo86VT1BagftmhK3_U

UICCAI-1512: added date ignore functionality for DFCX Test Builder assertion matching
